export type DisputeModel = {
    merchantName: string;
    contractNumber: string;
    arn: string;
    purchaseDate: string | null;
    registrationDate: string | null;
    cardNumber: string;
    // transactionType: ILookupResponse<number> | null;
    // currencyId: Currency;
    grossAmount: number;
    reasonCode: string;
    terminalId: string;
    dbaName: string;
    settlementNumber: string;
    agreementId: string;
    originalAmount: number;
    // originalCurrencyId: Currency | null;
    // cardType: ILookupResponse<number>;
    scheme: string;
    // disputeType: ILookupResponse<number>;
    responded: boolean;
    authorizationNumber: string;
    batchNumber: string;
    transactionNumber: number;
    isChargeback: boolean;
    isFinancial: boolean;
    isRepresentment: boolean;
    isReversal: boolean;
};
